// @ts-check
import { defineConfig } from 'astro/config';
import tailwindcss from '@tailwindcss/vite';

import cloudflare from '@astrojs/cloudflare';

// https://astro.build/config
export default defineConfig({
  site: 'https://onebrain.run',
  integrations: [],

  // Content-Security-Policy is generated by Astro, not the static
  // `_headers` file. Astro emits a per-page `<meta http-equiv>` CSP with
  // SHA-256 hashes for every `<script>`/`<style>` it renders — including
  // our `is:inline` blocks (Hero neural canvas, copy buttons, waitlist) —
  // so we no longer need `'unsafe-inline'` in script-src/style-src. That
  // closes the XSS amplifier the old `_headers` CSP carried.
  //
  // `directives` carries the non-script/style directives (Astro only
  // auto-manages script-src + style-src). External hosts go in
  // {script,style}Directive.resources, which Astro merges with the hashes.
  //
  // `frame-ancestors` is intentionally NOT listed: browsers ignore it in a
  // <meta> CSP, so clickjacking protection stays on `X-Frame-Options: DENY`
  // in `_headers`. `report-uri`/`report-to` are likewise meta-incompatible
  // and unused here.
  security: {
    csp: {
      algorithm: 'SHA-256',
      directives: [
        "default-src 'self'",
        "font-src 'self' https://fonts.gstatic.com data:",
        "img-src 'self' data:",
        "connect-src 'self' https://onebrain.run https://cloudflareinsights.com https://challenges.cloudflare.com",
        "frame-src https://challenges.cloudflare.com",
        "worker-src 'self'",
        "manifest-src 'self'",
        "media-src 'none'",
        "object-src 'none'",
        "base-uri 'self'",
        "form-action 'self'",
        'upgrade-insecure-requests',
      ],
      scriptDirective: {
        // 'self' + Astro-generated hashes + Cloudflare Web Analytics beacon
        // + Turnstile api.js. Hashes are appended automatically.
        resources: [
          "'self'",
          'https://static.cloudflareinsights.com',
          'https://challenges.cloudflare.com',
        ],
      },
      styleDirective: {
        // 'self' + Astro-generated hashes + Google Fonts stylesheet.
        resources: ["'self'", 'https://fonts.googleapis.com'],
      },
    },
  },

  // Trim every space, newline, and HTML comment between elements in
  // the production build. Critical-chain / FCP win since the document
  // payload shrinks.
  compressHTML: true,

  build: {
    // Inline every page's CSS (~18 KiB total) into the document head
    // so there's no second round-trip for render-blocking stylesheets.
    // Lighthouse flagged ~140ms of render-block + a 189ms critical-
    // path chain caused by Layout.css and the page-level CSS file
    // both blocking first paint; inlining eliminates both. Trade-off
    // is a slightly larger HTML payload, but at <20 KiB CSS the win
    // dominates on every metric (LCP, FCP, critical-chain depth).
    inlineStylesheets: 'always',
  },

  vite: {
    plugins: [tailwindcss()],
  },

  adapter: cloudflare(),
});